services:
  db:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE='mysql'
      - MYSQL_USER='root'
      - MYSQL_ROOT_PASSWORD=''
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root 
      timeout: 20s
      retries: 10
    volumes:
      - /tmp/djangoMysql/mysqld:/var/run/mysqld
      - ./db:/var/lib/mysql
  web:
    build: .
    depends_on:
            db:
                condition: service_healthy
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/djangoMysql
      - /tmp/djangoMysql/mysqld:/run/mysqld