services:
  db:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE='mysql'
      - MYSQL_USER='root'
      - MYSQL_ROOT_PASSWORD=''
    volumes:
      - /tmp/djangoMysql/mysqld:/var/run/mysqld
      - ./db:/var/lib/mysql
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/djangoMysql
      - /tmp/djangoMysql/mysqld:/run/mysqld
    depends_on:
      - db